### ISSUE TITLE
ダッシュボードのコードが一部反映されていない

### ISSUE THREAD

**Issue by natsukimizumoto** [eastclouddev/Server-Front#29]
実装通りにスタイルが反映されない箇所があり。
・ニュースカテゴリの表示
・コース画像の表示
・上記箇所のレスポンシブ対応

**Comment by Maik425** [comment]
@natsukimizumoto 
これって解決済みですか？

**Comment by natsukimizumoto** [comment]
@Maik425 
解決してないです

**Comment by natsukimizumoto** [comment]
@Maik425 
 マージの際にコンポーネントが重複して存在してしまい反映されなかったため不要なコンポーネントは削除。
 ・ニュースカテゴリの表示
・コース画像の表示
・上記箇所のレスポンシブ対応

ローカルホストの表示に反映されていることを確認。
